"""Build the click maps the app uses to tell "on her" from "empty space".

For every clip, all frames are merged into one coarse grid (one cell per CELL
pixels). A cell is "on her" if she covers it in any frame. The app lets clicks
on empty cells pass through to the apps behind her.

Writes app/renderer/masks.js. Run after tools/clean_clips.py.
"""

import json
import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
MEDIA = ROOT / "app" / "media"
OUT = ROOT / "app" / "renderer" / "masks.js"
CLIPS = ["idle1", "idle2", "focus", "drink", "stretch"]
if (MEDIA / "work.webm").exists():   # optional laptop clip for focus
    CLIPS.append("work")
CELL = 10
THRESHOLD = 64   # alpha above this counts as her


def size(path):
    out = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "v:0",
                          "-show_entries", "stream=width,height", "-of", "json", str(path)],
                         capture_output=True, text=True, check=True).stdout
    s = json.loads(out)["streams"][0]
    return s["width"], s["height"]


def union_alpha(path):
    w, h = size(path)
    # libvpx must be named as the decoder, or ffmpeg drops the alpha channel.
    p = subprocess.Popen(["ffmpeg", "-v", "error", "-c:v", "libvpx-vp9", "-i", str(path),
                          "-f", "rawvideo", "-pix_fmt", "rgba", "-"], stdout=subprocess.PIPE)
    acc = np.zeros((h, w), bool)
    n = w * h * 4
    while True:
        buf = p.stdout.read(n)
        if len(buf) < n:
            break
        acc |= np.frombuffer(buf, np.uint8).reshape(h, w, 4)[:, :, 3] > THRESHOLD
    p.wait()
    return acc


def main():
    masks = {}
    for name in CLIPS:
        a = union_alpha(MEDIA / f"{name}.webm")
        h, w = a.shape
        rows, cols = -(-h // CELL), -(-w // CELL)
        pad = np.zeros((rows * CELL, cols * CELL), bool)
        pad[:h, :w] = a
        grid = pad.reshape(rows, CELL, cols, CELL).any(axis=(1, 3))
        masks[name] = ["".join("1" if c else "0" for c in r) for r in grid]
        print(f"{name:8s} {cols}x{rows} cells, {grid.mean():.0%} on her")
    data = {"width": w, "height": h, "cell": CELL, "clips": masks}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("// Generated by tools/make_masks.py. Which parts of each clip are her.\n"
                   "window.BUDDY_MASKS = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
